server:
  port: 8084
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
        - id: company
          uri: lb://COMPANY
          predicates:
            - Path=/companies/**
        - id: user
          uri: lb://USER
          predicates:
            - Path=/users/**
        - id: employee
          uri: lb://EMPLOYEE
          predicates:
            - Path=/employees/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true